### ISSUE TITLE
project error, please help

### ISSUE THREAD

**Issue by vedatorkun** [atish-adhikari/Gallery-CRUD-in-CodeIgniter-with-MySQL-Datasbase#1]
> A PHP Error was encountered
Severity: Notice

Message: Undefined variable: record

Filename: views/index.php

Line Number: 367

Backtrace:

File: C:\wamp64\www\vedo\application\views\index.php
Line: 367
Function: _error_handler

File: C:\wamp64\www\vedo\application\controllers\Albums.php
Line: 19
Function: view

File: C:\wamp64\www\vedo\index.php
Line: 315
Function: require_once

A PHP Error was encountered
Severity: Notice

Message: Trying to get property of non-object

Filename: views/index.php

Line Number: 367

Backtrace:

File: C:\wamp64\www\vedo\application\views\index.php
Line: 367
Function: _error_handler

File: C:\wamp64\www\vedo\application\controllers\Albums.php
Line: 19
Function: view

File: C:\wamp64\www\vedo\index.php
Line: 315
Function: require_once

A PHP Error was encountered
Severity: Notice

Message: Undefined variable: picturelist

Filename: views/index.php

Line Number: 368

Backtrace:

File: C:\wamp64\www\vedo\application\views\index.php
Line: 368
Function: _error_handler

File: C:\wamp64\www\vedo\application\controllers\Albums.php
Line: 19
Function: view

File: C:\wamp64\www\vedo\index.php
Line: 315
Function: require_once

A PHP Error was encountered
Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: views/index.php

Line Number: 368

Backtrace:

File: C:\wamp64\www\vedo\application\views\index.php
Line: 368
Function: _error_handler

File: C:\wamp64\www\vedo\application\controllers\Albums.php
Line: 19
Function: view

File: C:\wamp64\www\vedo\index.php
Line: 315
Function: require_once

**Comment by atish-adhikari** [comment]
Warnings were generated, as we were trying to list albums, but arrays containing names of albums and images were empty initially.
A simple condition to check if the array is set and not empty before listing albums should solve the problem.
Also, to prevent upload issues, Make the following Folders manually in root folder.  uploads -> gallery -> thumbs.
Kindly download files from latest commit, and thanks for mentioning this issue.

**Comment by vedatorkun** [comment]
I tried to download the project again and this time there were different mistakes :( 
(note: the codeigniter I am using: 3.1.9) 

I do not understand what the problem is

**Comment by atish-adhikari** [comment]
So, you are trying to integrate this gallery into your bigger project? 
Please comment the errors!

**Comment by vedatorkun** [comment]
no, I just imported the database (gallery_ci.sql) to examine this project and changed the database information (application\config\database.php) in the project (localhost, root), that's all.

no, I just imported the database to examine this project and changed the database information in the project (localhost, root), that's all. The following faults have been initiated since the clean installation.

----------------------------------------------------------------------------------------------------------
`A PHP Error was encountered
Severity: Warning

Message: include(\partials\header.php): failed to open stream: No such file or directory

Filename: views/index.php

Line Number: 4`
----------------------------------------------------------------------------------------------------------
`A PHP Error was encountered
Severity: Warning

Message: include(): Failed opening '\partials\header.php' for inclusion (include_path='.;C:\php\pear')

Filename: views/index.php

Line Number: 4`
----------------------------------------------------------------------------------------------------------
`A PHP Error was encountered
Severity: Warning

Message: include(\partials\navbar.php): failed to open stream: No such file or directory

Filename: views/index.php

Line Number: 5`
----------------------------------------------------------------------------------------------------------
`A PHP Error was encountered
Severity: Warning

Message: include(): Failed opening '\partials\navbar.php' for inclusion (include_path='.;C:\php\pear')

Filename: views/index.php

Line Number: 5`
----------------------------------------------------------------------------------------------------------
`A PHP Error was encountered
Severity: Warning

Message: include(\templates\album.php): failed to open stream: No such file or directory

Filename: views/index.php

Line Number: 9`
----------------------------------------------------------------------------------------------------------
`A PHP Error was encountered
Severity: Warning

Message: include(): Failed opening '\templates\album.php' for inclusion (include_path='.;C:\php\pear')

Filename: views/index.php

Line Number: 9`
----------------------------------------------------------------------------------------------------------
`A PHP Error was encountered
Severity: Warning

Message: include(\partials\footer.php): failed to open stream: No such file or directory

Filename: views/index.php

Line Number: 14`
----------------------------------------------------------------------------------------------------------
A PHP Error was encountered
Severity: Warning

Message: include(): Failed opening '\partials\footer.php' for inclusion (include_path='.;C:\php\pear')

Filename: views/index.php

Line Number: 14

**Comment by atish-adhikari** [comment]
Your PHP configuration was not allowing use of relative paths in include statement. The issue has been fixed by using `__DIR__` magic constant, which returns the directory of file, and concatenating this to rest of the path.
Let me know if this does/doesn't solve the problem.
